# this is just a simple test device setup that's used to compile and test the examples

esphome:
  name: external-components-test-device

# esp32:
#   board: esp32dev
#   framework:
#     type: esp-idf
esp8266:
  board: d1

wifi:
  ssid: !secret home_wifi_ssid
  password: !secret home_wifi_password
  manual_ip:
    static_ip: 192.168.160.145
    gateway: 192.168.160.1
    subnet: 255.255.255.0

web_server:
  port: 80
  version: 3
